// src/routes/__root.tsx
//
// WHY THIS FILE CHANGED:
//
// The original file used two TanStack Start SSR patterns that don't exist
// in a plain Vite SPA build:
//
//   1. `import appCss from "../styles.css?url"`
//      In SSR/Cloudflare mode, `?url` imports the CSS as a URL string so the
//      server can inject it into the <head> before streaming HTML.
//      In a Vite SPA build, Vite handles CSS automatically — just import the
//      file normally and Vite will bundle + inject it.
//      The `href: appCss` entry in `head.links` is also removed because
//      Vite's SPA mode already emits a <link rel="stylesheet"> via its asset
//      pipeline; having it twice would double-load styles.
//
//   2. `shellComponent: RootShell` with `<HeadContent />` and `<Scripts />`
//      These are TanStack Start SSR APIs that let the server control the outer
//      <html> shell. They are NOT available in @tanstack/react-router (SPA).
//      In SPA mode, the <html> / <head> / <body> wrapper lives in index.html
//      (auto-generated by Vite). The RootShell component is removed and
//      `shellComponent` is dropped from the route definition.
//      `HeadContent` and `Scripts` imports are also removed.
//
// Everything else (meta tags, fonts, NotFoundComponent, ErrorComponent,
// QueryClientProvider) is unchanged.

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import {
  Outlet,
  Link,
  createRootRouteWithContext,
  useRouter,
} from "@tanstack/react-router";

// Normal CSS import — Vite bundles and injects this automatically in SPA mode.
import "../styles.css";

function NotFoundComponent() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-7xl font-bold text-foreground">404</h1>
        <h2 className="mt-4 text-xl font-semibold text-foreground">
          Page not found
        </h2>
        <p className="mt-2 text-sm text-muted-foreground">
          The page you're looking for doesn't exist or has been moved.
        </p>
        <div className="mt-6">
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Go home
          </Link>
        </div>
      </div>
    </div>
  );
}

function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) {
  console.error(error);
  const router = useRouter();

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-xl font-semibold tracking-tight text-foreground">
          This page didn't load
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Something went wrong on our end. You can try refreshing or head back
          home.
        </p>
        <div className="mt-6 flex flex-wrap justify-center gap-2">
          <button
            onClick={() => {
              router.invalidate();
              reset();
            }}
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Try again
          </button>
          <a
            href="/"
            className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
          >
            Go home
          </a>
        </div>
      </div>
    </div>
  );
}

export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()(
  {
    head: () => ({
      meta: [
        { charSet: "utf-8" },
        { name: "viewport", content: "width=device-width, initial-scale=1" },
        { title: "DO NOT PRESS — A Birthday Experience for Joshua" },
        {
          name: "description",
          content:
            "A classified interactive birthday tribute to Joshua. Do not press the button.",
        },
        { name: "author", content: "For Joshua" },
        {
          property: "og:title",
          content: "DO NOT PRESS — A Birthday Experience for Joshua",
        },
        {
          property: "og:description",
          content:
            "A classified interactive birthday tribute to Joshua. Do not press the button.",
        },
        { property: "og:type", content: "website" },
        { name: "twitter:card", content: "summary" },
        { name: "twitter:site", content: "@Lovable" },
        {
          name: "twitter:title",
          content: "DO NOT PRESS — A Birthday Experience for Joshua",
        },
        {
          name: "twitter:description",
          content:
            "A classified interactive birthday tribute to Joshua. Do not press the button.",
        },
        {
          property: "og:image",
          content:
            "https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/69c90aad-ac3c-4784-9ba7-5de43a373a81/id-preview-55ffd887--11ea7ca5-3c5d-47f2-9e74-e9f01c5a9bdc.lovable.app-1779276338581.png",
        },
        {
          name: "twitter:image",
          content:
            "https://pub-bb2e103a32db4e198524a2e9ed8f35b4.r2.dev/69c90aad-ac3c-4784-9ba7-5de43a373a81/id-preview-55ffd887--11ea7ca5-3c5d-47f2-9e74-e9f01c5a9bdc.lovable.app-1779276338581.png",
        },
      ],
      links: [
        // Google Fonts — loaded at runtime, not via ?url, so these are fine in SPA mode.
        { rel: "preconnect", href: "https://fonts.googleapis.com" },
        {
          rel: "preconnect",
          href: "https://fonts.gstatic.com",
          crossOrigin: "anonymous",
        },
        {
          rel: "stylesheet",
          href: "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght,SOFT,WONK@9..144,400..900,0..100,0..1&family=Fredoka:wght@300..700&family=Caveat:wght@400..700&family=JetBrains+Mono:wght@400;700&display=swap",
        },
      ],
    }),
    // shellComponent removed — SPA mode uses Vite's index.html as the shell.
    component: RootComponent,
    notFoundComponent: NotFoundComponent,
    errorComponent: ErrorComponent,
  },
);

function RootComponent() {
  const { queryClient } = Route.useRouteContext();

  return (
    <QueryClientProvider client={queryClient}>
      <Outlet />
    </QueryClientProvider>
  );
}
